### ISSUE TITLE
Add DOT country for POR

### ISSUE THREAD

**Issue by nishaj** [opentraveldata/opentraveldata#1]
Please add the DOT country code (US Department for Transportation code for a country).

Please find the link below for the Airport code to DOT mapping

http://www.dot.gov/sites/dot.dev/files/docs/airports_codes.txt

**Comment by wsteitz** [comment]
The linked CSV provides a mapping between IATA airport code and a numeric area code.I guess you want this to be added to the optd_por_public.csv file, correct? 

The optd_por_public.csv file is created using the tools/make_optd_por_public.sh and tools/make_optd_por_public.awk script. To add the DOT area codes, those scripts need to be adapted. The procedure should be similar to how other information (e.g. page rank values) are added to each por entry.

The CSV from DOT could be stored in 'data/dot/' and/or a script located there could fetch the latest data from the dot.gov site. 

Pull requests are welcome ;-)

**Comment by denisarnaud** [comment]
The [data/countries/DOT](http://github.com/opentraveldata/opentraveldata/data/countries/DOT) directory has been added.

**Comment by denisarnaud** [comment]
The US DOT World Area Code (WAC), and its corresponding name, are now fully integrated within the OpenTravelData (OPTD) POR data file. See af196e953a54264afa422757ccade69e66464e9f for more details.

**Comment by denisarnaud** [comment]
Some users would rather have the WAC-related fields appended at the end of the file, rather than inserted into it. So, a Doodle poll has been organised: https://doodle.com/myhf5g5e5afnwreu

**Comment by denisarnaud** [comment]
A Wikipedia page was created: http://en.wikipedia.org/wiki/US_DOT_WAC
