### ISSUE TITLE
ISL is duplicated

### ISSUE THREAD

**Issue by alexprengere** [opentraveldata/opentraveldata#100]
Hello,
In the latest revision of the file, two airports have the IATA code ISL:
* Isabel Pass Airport
* Istanbul New Airport

If I understand correctly, I think Isabel Pass Airport should have its "date_until" field set, so ISL could get attributed to Istanbul New Airport.

**Comment by denisarnaud** [comment]
Thanks, good catch!
Fixed by now

**Comment by alexprengere** [comment]
Thanks! I pushed a [test](https://github.com/alexprengere/neobase/commit/2f7c308cc1880666fa6d02ebc5010e8ec6aa829e) in NeoBase to catch any airport code duplication on future updates.
