### ISSUE TITLE
Please add VK -  Anisec Luftfahrt to the optd_airlines.csv file

### ISSUE THREAD

**Issue by deepak0000** [opentraveldata/opentraveldata#103]
Hello,

Please could you add VK -  Anisec Luftfahrt your optd_airlines.csv file?
Wiki link for reference - https://en.wikipedia.org/wiki/Anisec_Luftfahrt

Currently, VK is assigned to Air Nigeria - they've ceased operations (in 2012).

Best,
Deepak

**Comment by denisarnaud** [comment]
e425195d72fd8cd213 fixes the issue
