### ISSUE TITLE
Asia/Qostanay timezone

### ISSUE THREAD

**Issue by alexprengere** [opentraveldata/opentraveldata#106]
In the recent commits a new timezone was added to the file: Asia/Qostanay. `pytz` does not recognize this, so I guess this timezone does not exist.

Concerned points of reference are: AYK, BXY, KSN.

**Comment by denisarnaud** [comment]
Thanks for pointing out that change!
Note that this time-zone exists on some specialized web-sites, for instance http://worldtimeapi.org/timezone/Asia/Qostanay
And picking on Geonames one of the examples you mentioned, namely [Arkalyk North Airport (AYK)](http://www.geonames.org/7668495), Geonames actually references that apparently new time-zone.

Further checking, that time-zone is referenced on Wikipedia ([Time in Kazakhstan](https://en.wikipedia.org/wiki/Time_in_Kazakhstan)). Digging around the `tz` database (on [Wikipedia](https://en.wikipedia.org/wiki/Tz_database) and on the [official IANA web-site](https://www.iana.org/time-zones)), I found out that this new time-zone has been added last December (2018), with the 2018h release of the `tz` database: http://mm.icann.org/pipermail/tz-announce/2018-December/000053.html
I guess that Geonames has subscribed to [the `tz announce` mailing list](http://mm.icann.org/pipermail/tz-announce/).
The records for Kazakhstan are:
```bash
$ mkdir ~/tmp/tzdata && cd ~/tmp/tzdata
$ wget https://data.iana.org/time-zones/releases/tzdata2018i.tar.gz
$ tar zxf tzdata2018i.tar.gz && rm -f tzdata2018i.tar.gz
$ grep "^KZ" zone.tab 
KZ      +4315+07657     Asia/Almaty     Kazakhstan (most areas)
KZ      +4448+06528     Asia/Qyzylorda  Qyzylorda/Kyzylorda/Kzyl-Orda
KZ      +5312+06337     Asia/Qostanay   Qostanay/Kostanay/Kustanay
KZ      +5017+05710     Asia/Aqtobe     Aqtobe/Aktobe
KZ      +4431+05016     Asia/Aqtau      Mangghystau/Mankistau
KZ      +4707+05156     Asia/Atyrau     Atyrau/Atirau/Gur'yev
KZ      +5113+05121     Asia/Oral       West Kazakhstan
```

**Comment by alexprengere** [comment]
You are absolutely correct, I did not update `pytz` before running the tests. After doing so, everything is fine, sorry for the trouble.
