### ISSUE TITLE
TSF city codes, similar issue to EWR and SWF

### ISSUE THREAD

**Issue by Steve-Z** [opentraveldata/opentraveldata#107]
#61 
Similar to SWF where you changed order of city code list to put NYC first, Treviso (TSF) lists city code TSF _before_ VCE (Venice), but https://www.iata.org/publications/Pages/code-search.aspx shows VCE as the city code. I think you should change this order as well and put VCE first. In working with API's it would be nice to know that city_code_list[0] is the most correct choice. 

Is there a way to check optd_por_public.csv for consistency in this regard? Here is what I generated by looking for IATA aiport codes with more than one city code:

`{'name': 'Amman Civil Airport', 'city_code': ['AMM', 'ADJ']}
{'name': 'Phoenix-Mesa Gateway Airport', 'city_code': ['PHX', 'MSC']}
{'name': "Qionghai Bo'ao Airport", 'city_code': ['BAR', 'BPO']}
{'name': 'Wings Field', 'city_code': ['PHL', 'BBX']}
{'name': 'Bradley International Airport', 'city_code': ['HFD', 'BDL', 'SFY']}
{'name': 'Rocky Mountain Metropolitan Airport', 'city_code': ['DEN', 'BJC']}
{'name': 'Bisbee Municipal Airport', 'city_code': ['BSQ', 'DUG']}
{'name': 'Baltimore-Washington International Airport', 'city_code': ['BWI', 'WAS']}
{'name': 'Madinaty Capital International Airport', 'city_code': ['CAI', 'CCE']}
{'name': 'Westover Air Reserve Base / Metropolitan Airport', 'city_code': ['SFY', 'CEF']}
{'name': 'Clearwater Air Park', 'city_code': ['CLW', 'TPA']}
{'name': 'Dallas/Fort Worth International Airport', 'city_code': ['DFW', 'FTW']}
{'name': 'Blaise Diagne International Airport', 'city_code': ['DKR', 'DSS']}
{'name': 'Murray Field', 'city_code': ['EKA', 'ACV']}
{'name': 'Ankara Esenboğa International Airport', 'city_code': ['ANK', 'ESB']}
{'name': 'Brighton Shoreham Airport', 'city_code': ['ESH', 'BSH']}
{'name': 'Essen/Mülheim Airport', 'city_code': ['ESS', 'ZOO']}
{'name': 'Newark Liberty International Airport', 'city_code': ['NYC', 'EWR', 'ZME']}
{'name': 'Alpes–Isère Airport', 'city_code': ['GNO', 'LYS']}
{'name': 'Glentanner Airport', 'city_code': ['MON', 'GTN']}
{'name': 'Düsseldorf Mönchengladbach Airport', 'city_code': ['DUS', 'MGL']}
{'name': 'Falcon Field', 'city_code': ['MSC', 'PHX']}
{'name': 'Martin State Airport', 'city_code': ['BWI', 'WAS']}
{'name': 'Minatitlán/Coatzacoalcos International Airport', 'city_code': ['MTT', 'QTZ']}
{'name': 'Kneeland Airport', 'city_code': ['ACV', 'EKA']}
{'name': 'Niederrhein Weeze Airport', 'city_code': ['DUS', 'NRN']}
{'name': 'Narvik Airport, Framnes', 'city_code': ['EVE', 'NVK']}
{'name': 'Ontario International Airport', 'city_code': ['LAX', 'ONT']}
{'name': 'Newport News-Williamsburg International Airport', 'city_code': ['PHF', 'LFI', 'ZWB']}
{'name': 'Portsmouth International Airport at Pease', 'city_code': ['BOS', 'PSM']}
{'name': 'Manuel Carlos Piar Guayana Airport', 'city_code': ['PZO', 'SFX']}
{'name': 'Frankfurt Egelsbach Airport', 'city_code': ['FRA', 'QEF']}
{'name': 'Chicago/Rockford International Airport', 'city_code': ['CHI', 'RFD']}
{'name': 'Región de Murcia International Airport', 'city_code': ['MJV', 'RMU']}
{'name': 'Salisbury–Ocean City–Wicomico Regional Airport', 'city_code': ['OCE', 'SBY']}
{'name': 'Scottsdale Airport', 'city_code': ['PHX', 'SCF']}
{'name': 'Spartanburg Downtown Memorial Airport', 'city_code': ['SPA', 'GSP']}
{'name': 'Albert Whitted Airport', 'city_code': ['SPG', 'TPA']}
{'name': 'Giza Sphinx International Airport', 'city_code': ['CAI', 'SPX']}
{'name': 'Richard I. Bong Airport', 'city_code': ['SUW', 'DLH']}
{'name': 'Stewart International Airport', 'city_code': ['NYC', 'SWF']}
{'name': 'Licenciado Adolfo López Mateos International Airport', 'city_code': ['MEX', 'TLC']}
{'name': 'Toussus-le-Noble Airport', 'city_code': ['TNF', 'PAR']}
{'name': 'Treviso Airport', 'city_code': ['TSF', 'VCE']}
{'name': 'Portland–Troutdale Airport', 'city_code': ['TTD', 'PDX']}
{'name': 'Playa Baracoa Airport', 'city_code': ['HAV', 'UPB']}
{'name': 'Valle Airport', 'city_code': ['GCN', 'VLE']}
{'name': 'Juan Gualberto Gómez International Airport', 'city_code': ['VRA', 'QMA']}
{'name': 'Zunyi Maotai Airport', 'city_code': ['ZYI', 'WMT']}
{'name': 'Zhukovsky International Airport', 'city_code': ['MOW', 'ZIA']}
>>> 
`

**Comment by denisarnaud** [comment]
Good catch, thanks!
We could sort those cities by PageRank values. For instance, with TSF and VCE:
```bash
grep -e "^VCE" -e "^TSF" optd_por_public.csv |cut -d'^' -f1,1 -f12,13
TSF^AIRP^0.016826084671924372
TSF^PPLA2^
VCE^AIRP^0.06250188265755892
VCE^PPLA^0.07647339343886088
```
And AMM ADJ:
```bash
grep -e "^AMM" -e "^ADJ" optd_por_public.csv |cut -d'^' -f1,1 -f12,13
ADJ^AIRP^0.002873814530368673
ADJ^PPLX^0.002873814530368673
AMM^AIRP^0.05657950404454336
AMM^PPLC^0.05659874468428967
```
I would rather recommend to manually edit the [`opentraveldata/optd_por_best_known_so_far.csv` file](https://github.com/opentraveldata/opentraveldata/blob/master/opentraveldata/optd_por_best_known_so_far.csv). If I remember correctly, we had such a discussion at some point in time, and we concluded that editing manually provides better control on the results, given that the number of involved POR is not so high. See [Adam's comment on the still open issue](https://github.com/opentraveldata/opentraveldata/issues/12#issuecomment-229091844].

**Comment by denisarnaud** [comment]
And do not hesitate to add a script in [Open Travel Data (OPTD) Quality Assurance (QA) checkers](https://github.com/opentraveldata/quality-assurance/tree/master/checkers).
You can take inspiration on https://github.com/opentraveldata/quality-assurance/blob/master/checkers/check-por-cmp-optd-unlc.py
The README in https://github.com/opentraveldata/quality-assurance explains how to set up the environment, either natively or through Docker.

**Comment by Steve-Z** [comment]
I took your advice and manually went through airports with more than one city code. I used [optd_por_best_know_so_far.csv](https://github.com/opentraveldata/opentraveldata/blob/master/opentraveldata/optd_por_best_known_so_far.csv) as my source, and checked codes at the [IATA search page](https://www.iata.org/publications/Pages/code-search.aspx).

First, I used this short Python script to find airports with multiple city codes:
[iata_best_codes.py.txt](https://github.com/opentraveldata/opentraveldata/files/2743101/iata_best_codes.py.txt)

I then manually went through each airport code(key) in the json file. I used my own legend for each type of problem or error. I then sorted them out with another short script:
[multicity_errors.py.txt](https://github.com/opentraveldata/opentraveldata/files/2743105/multicity_errors.py.txt)

The most common reason multiple city codes occur seems to be when a secondary airport is associated with a city that is also a code for the primary airport, e.g., ONT: LAX, ONT. 

LAX (Los Angeles) is the correct city code; ONT is **not** a city code but rather the eponymous airport code. Not sure why it was done this way? Generated by a tool script? _I did not consider these to be in error_. This makes sense so long an actual city code comes first.

Here is the output of my error checking script:

Change order (correct city code, but it should come before eponymous airport code to be consistent):
	BAF: ['BAF', 'SFY']
	BDL: ['HFD', 'BDL', 'SFY']  _BDL serves Hartford and Springfield, but BDL should come last_
	BSQ: ['BSQ', 'DUG']
	BVV: ['BVV', 'ITU']
	CLW: ['CLW', 'TPA']
	EKA: ['EKA', 'ACV']
	FSI: ['FSI', 'LAW']
	GNB: ['GNO', 'LYS']
	HPV: ['LIH', 'HPV']
	MSC: ['MSC', 'PHX']
	POB: ['FAY', 'FBG']
	SPA: ['SPA', 'GSP']
	SPG: ['SPG', 'TPA']
	TTD: ['TTD', 'PDX']

Contains typo or code not assoc with this airport:
	AZA: ['PHX', 'MSC']
	GNB: ['GNO', 'LYS']  _Typo. GNO should be GNB_
	HPV: ['LIH', 'HPV']
	LNE: ['LNE', 'SSR']
	MTN: ['BWI', 'WAS']
	NLN: ['ACV', 'EKA']
	PHF: ['PHF', 'LFI', 'ZWB']
	POB: ['FAY', 'FBG']
	PZO: ['PZO', 'SFX']
	RMU: ['MJV', 'RMU']
	SBY: ['OCE', 'SBY']
	SUW: ['SUW', 'DLH']
	SZN: ['SBA', 'SZN']
	TNF: ['TNF', 'PAR']
	VDA: ['VDA', 'ETH']

These airports legitimately serve 2 cities:
	BDL: ['HFD', 'BDL', 'SFY']
	BWI: ['BWI', 'WAS']
	DFW: ['DFW', 'FTW']

Contains code for which IATA.org search finds "No results" (last one in each case):
	ESH: ['ESH', 'BSH']
	ESS: ['ESS', 'ZOO']
	EWR: ['NYC', 'EWR', 'ZME']
	MTT: ['MTT', 'QTZ']
        PHF: ['PHF', 'LFI', 'ZWB'] 
	QEF: ['FRA', 'QEF']  _QEF is not found at IATA_
	VRA: ['VRA', 'QMA']

These seem to be military airfields:
	BVV: ['BVV', 'ITU']
	FSI: ['FSI', 'LAW']
	NLU: ['MEX', 'NLU']
	NUW: ['ODW', 'NUW']
	PHF: ['PHF', 'LFI', 'ZWB']  _PHF is correct but LFI is military and ZWB = "no results"_
	WRB: ['MCN', 'WRB']

Any suggestions for next step. I can make edits if someone explains how. I haven't seen pull requests in this repository. Isn't that how it's done? Or is there another way. Advice would be appreciated.

**Comment by denisarnaud** [comment]
Many thanks, Steve, for that contribution!

Yes, you can for sure submit pull requests, and in the past, [quite a few have been submitted already](https://github.com/opentraveldata/opentraveldata/pulls?q=is%3Apr+is%3Aclosed).

I took the opportunity of your submitted source code to add a few checkers in the [Quality Assurance project](https://github.com/opentraveldata/quality-assurance). The details may be checked in the [QA project documentation update](https://github.com/opentraveldata/quality-assurance/commit/ca41cd5699b1b99ada0c07db5f757bb152fe8521). In particular:
* [OPTD consistency and Geonames ID](https://github.com/opentraveldata/quality-assurance/blob/master/README.md#optd-consistency-and-geonames-id)
* [City POR not in OPTD](https://github.com/opentraveldata/quality-assurance/blob/master/README.md#city-por-not-in-optd)
* [Multi-city POR in OPTD](https://github.com/opentraveldata/quality-assurance/blob/master/README.md#multi-city-por-in-optd)

Moreover, note that the [IATA code search page](https://www.iata.org/publications/Pages/code-search.aspx) references only airports (and not, say railway or bus stations, heliports, ferry ports and off-line points). The other types of location referenced by IATA have to be found by other means (e.g., GCM, OurAirports, Wikipedia); if you PM me, I may help you if you want to know more.
The latest files of IATA-referenced POR details can be found in the [`data/IATA/archives` directory](https://github.com/opentraveldata/opentraveldata/tree/master/data/IATA/archives). It corresponds to best effort research.

Also, note that on the [IATA code search page](https://www.iata.org/publications/Pages/code-search.aspx), there are always two set of columns, one of them corresponding to the city and the other  one to the airport (as, again, no other type of location is shown on that web page). It means that, for all the POR (points of reference), there is at least an associated city. And when there are multiple POR servicing the city, that latter is called by IATA a metropolitan area (such as Chicago, London and Paris).

You may also be interested in the discussion about [(IATA) location identifiers on Wikipedia/Wikidata](https://www.wikidata.org/wiki/Property_talk:P238#IATA_Location_Identifier).

**Comment by denisarnaud** [comment]
I just added a clause in the [`checkers/check-por-multiple-cities.py` QA script](https://github.com/opentraveldata/quality-assurance/blob/master/checkers/check-por-multiple-cities.py), so as to generate the records for which the sorting order of cities is not following PageRank values. A [copy of the resulting `optd-qa-por-multi-city-not-std.csv` file is available here](https://github.com/opentraveldata/opentraveldata/files/2747134/optd-qa-por-multi-city-not-std.txt). There are currently 29 such records (out of 90 multi-city POR).

**Comment by Steve-Z** [comment]
Hi I do have some follow up questions. I am happy to PM you rather than fill comments here in a closed issue. How should I do that? I found an m4x.org email in your public github data here: https://api.github.com/users/denisarnaud/events/public

Is that email a good way to communicate? Thanks.

**Comment by denisarnaud** [comment]
Yes, that is the one!
