### ISSUE TITLE
Issue with LH IATA code for both Lufthansa and Lufthansa Cargo

### ISSUE THREAD

**Issue by deepak0000** [opentraveldata/opentraveldata#109]
Hello,

In the optd_airlines.csv file, we notice that 'LH' is assigned as the IATA code for both Lufthansa _and_ Lufthansa Cargo, with both entries valid (according to the validity from and to dates) - this is causing a few problems with the way the reference lookups work, so please could you remove the IATA code for Lufthansa Cargo?
If this cannot be done, please could you populate the 'type' column in the same file against the Lufthansa Cargo entry so that we can correctly identify it?

Best,
Deepak

**Comment by denisarnaud** [comment]
Thanks Deepak for your contribution!
That one is a tricky one. At the time, I searched extensively, and found out that Lufthansa Cargo has actually got the exact same IATA code as Lufthansa Passage. So, I implemented your other suggestion, i.e., specifying the airline type ('P' for Lufthansa Passage and 'C' for Lufthansa Cargo).
