### ISSUE TITLE
CKW-YCHK (Christmas Creek Mine) IATA-ICAO mapping

### ISSUE THREAD

**Issue by 743** [opentraveldata/opentraveldata#11]
Mapping to ICAO (YCHK) for CKW airport is missing even though the mapping is present in geonames(http://www.geonames.org/maps/google_-22.3525_119.63883.html).

**Comment by denisarnaud** [comment]
Thanks!

As a matter of fact, the name of that airport seems to be actually Graeme Rowley Airport: http://www.geonames.org/10375662/graeme-rowley-airport.html
