### ISSUE TITLE
BF IATA code incorrectly mapped to BlueBird Cargo

### ISSUE THREAD

**Issue by deepak0000** [opentraveldata/opentraveldata#110]
Hello,
It looks like the IATA code 'BF' is incorrectly mapped to BlueBird Cargo - a quick check on Wikipedia and the IATA codes page reveals that it's actually 'BO'. Please could you make the change?

Wiki -> https://en.wikipedia.org/wiki/Bluebird_Nordic
IATA -> https://www.iata.org/publications/Pages/code-search.aspx

Thank you in advance! 
Best,
Deepak

**Comment by denisarnaud** [comment]
Good catch, thanks for your contribution, Deepak!
