### ISSUE TITLE
Wrong fcode for NBP: New York NY US Battery Park City

### ISSUE THREAD

**Issue by Steve-Z** [opentraveldata/opentraveldata#111]
In [optd_por_public.csv](https://github.com/opentraveldata/opentraveldata/blob/master/opentraveldata/optd_por_public.csv), this line
`NBP^^^N^0^^New York NY US Battery Pk City^New York NY US Battery Pk City^40.73^-73.97^S^AIRP^`
shows this POR as AIRP. There is no airport at this location. Perhaps this is a heliport that has been mislabeled. 

I see that `'is_geonames' == 'N'` for NBP. I wonder if filtering out `'is_geonames' == 'N'` is a good strategy when looking for working airports?

**Comment by denisarnaud** [comment]
Thanks for that contribution!

Yes, some POR (points of reference) types are wrong, and we always welcome when contributors suggest to fix those errors 👍
