### ISSUE TITLE
Please update I9 and IG in the optd_airlines.csv file

### ISSUE THREAD

**Issue by deepak0000** [opentraveldata/opentraveldata#114]
Hello,

Air Italy is currently mapped to I9 -> This needs to be changed to IG, it looks like they changed their designator on March 1, 2018.
Meridiana is another airline that needs to have it's "validity_to" date updated to March 1, 2018 after it was rebranded to IG.

Best,
Deepak

**Comment by deepak0000** [comment]
Please note that the ICAO code for Air Italy has also changed - from AEY to ISS.

**Comment by deepak0000** [comment]
Hello,
Gentle reminder for updating the above entries.
Best,
Deepak

**Comment by denisarnaud** [comment]
For the record, the new airline (https://en.wikipedia.org/wiki/Air_Italy) (IATA: IG; ICAO: ISS; accounting code: 191) is a merge (as of March 2018) of:
* Air Italy (https://en.wikipedia.org/wiki/Air_Italy_(2005%E2%80%932018))(IATA: I9; ICAO: AEY; accounting code: 67)
* Meridiana (https://en.wikipedia.org/wiki/Meridiana)(IATA: IG; ICAO: ISS; accounting code: 191)

**Comment by denisarnaud** [comment]
Do not hesitate, if you want to quicken the process, to directly contribute, for instance with a pull request (https://github.com/opentraveldata/opentraveldata/pulls) on both https://github.com/opentraveldata/opentraveldata/blob/master/opentraveldata/optd_airline_best_known_so_far.csv and https://github.com/opentraveldata/opentraveldata/blob/master/opentraveldata/optd_airline_no_longer_valid.csv . I can the generate the resulting https://github.com/opentraveldata/opentraveldata/blob/master/opentraveldata/optd_airlines.csv file (by running https://github.com/opentraveldata/opentraveldata/blob/master/tools/make_optd_airline_public.py)

**Comment by denisarnaud** [comment]
https://www.businessinsider.de/american-airlines-ceo-air-italy-qatar-airways-violate-openskies-2019-5
