### ISSUE TITLE
Missing geocodes in latest file

### ISSUE THREAD

**Issue by alexprengere** [opentraveldata/opentraveldata#115]
Latest file has 2 por without geocodes: IST and ISL.

**Comment by denisarnaud** [comment]
Good catch, thanks!

Most of the operations have moved from the [old Istanbul airport](https://en.wikipedia.org/wiki/Istanbul_Atat%C3%BCrk_Airport) to [the new one](https://en.wikipedia.org/wiki/Istanbul_Airport), and the IATA codes (ISL and IST) have been swapped accordingly: IST has therefore always been assigned to the main airport.

**Comment by denisarnaud** [comment]
A new [Python checker](https://github.com/opentraveldata/quality-assurance/blob/master/checkers/check-por-optd-no-geocoord.py) has been added to the [OPTD Quality Assurance (QA) project](https://github.com/opentraveldata/quality-assurance), checking for POR missing geo-location.
The logs of the [Travis CI runner](https://travis-ci.com/opentraveldata/quality-assurance) may be checked to see the outcome of all the checkers, which includes that one in particular (search for the `results/optd-qa-por-optd-no-geocoord.csv` file).
