### ISSUE TITLE
Correct name for Cathay Dragon [airline]

### ISSUE THREAD

**Issue by Steve-Z** [opentraveldata/opentraveldata#117]
Should entry for Cathay Dragon Airline (KA), previously known as Dragonair, be updated? Line 370 of [optd_airline_best_known_so_far.csv](https://github.com/opentraveldata/opentraveldata/blob/master/opentraveldata/optd_airline_best_known_so_far.csv):
`air-dragonair-v1^^1985-07-01^^HDA^KA^43^Hong Kong Dragon Airlines^^^Affiliate^^https://en.wikipedia.org/wiki/Cathay_Dragon^en|Hong Kong Dragon Airlines|p=en|Cathay Dragon|h=en|Dragonair|h^HKG^air-dragonair^1^`
Per Wikipedia "Hong Kong Dragon Airlines Limited, branded as Cathay Dragon and previously as Dragonair, is a Hong Kong-based international regional airline." I believe the name change is related to Cathay Pacific's acquisition in 2006. So should this csv use the branded name - Cathay Dragon - or  continue with the corporate subsidiary (Hong Kong Dragon Airlines) name? I would be happy to fix this with a pull request if the change is appropriate.

**Comment by denisarnaud** [comment]
Thanks for your contribution!
For the record, the Wikipedia page is https://en.wikipedia.org/wiki/Cathay_Dragon
