### ISSUE TITLE
Viva Air Colombia code change (FC => VH)

### ISSUE THREAD

**Issue by Camusensei** [opentraveldata/opentraveldata#121]
Hello.

This airline changed code at the beginning of the year and not much communication was done around it.
I opened PR #120 to fix this issue, please have a look.

Regards,
Alexandre

**Comment by denisarnaud** [comment]
Many thanks for the contribution!

Just a few minor issues:
* When moved into non active airlines, an envelope ID should be added. When it is the first airline for that key to be retired, the envelope ID is 1. Then it increments for every next version.
* The alternate name section follows the pattern `lang-code|Name|qualifier`, where the qualifier may be any of empty, `p` (preferred version), `s` (short version) , `h` (historical). For call-signs, the `sign` language code is used. Several alternate names may be chained; the `=` (equal sign) is used to separate all the alternative expressions.
