### ISSUE TITLE
Missing airport Kulhudhuffushi (IATA HDK)

### ISSUE THREAD

**Issue by pjburon** [opentraveldata/opentraveldata#122]
Hello,

The Maldivian airport Kulhudhuffushi (IATA code HDK) is missing.

According to maldivestimes (https://maldivestimes.com/scheduled-flights-to-kulhudhuffushi-airport-to-begin-on-friday/) flights can be scheduled from 2019-08-09.

Regards
Pierre-Jean Buron

**Comment by denisarnaud** [comment]
Thanks for the heads up!

For the record:
* Kulhudhuffushi Airport: https://www.geonames.org/12076772 / https://en.wikipedia.org/wiki/Kulhudhuffushi_Airport
* Kulhudhuffushi: https://www.geonames.org/1337613 / https://en.wikipedia.org/wiki/Kulhudhuffushi
