### ISSUE TITLE
Maldivian airport Maafaru missing (IATA NMF)

### ISSUE THREAD

**Issue by pjburon** [opentraveldata/opentraveldata#123]
Hello,

The Maldivian international new airport Maafaru (IATA code NMF) is missing in the file `optd_por_public.csv`.
The airport has opened in September 2019.

Regards
Pierre-Jean Buron

**Comment by denisarnaud** [comment]
Thanks for the heads up!
For the record:
* [Maafaru International Airport on Geonames](https://www.geonames.org/12088696/maafaru-international-airport.html)
* [Maafaru Island on Geonames](https://www.geonames.org/1282064/maafaru-island.html)

The OPTD POR file will be updated tomorrow, once the new snapshot of Geonames will have been generated.
