### ISSUE TITLE
optd_airlines.csv update for Z7

### ISSUE THREAD

**Issue by jcartgrandjean** [opentraveldata/opentraveldata#125]
Hello,
I have an update for optd_airlines.csv for two small airlines. 
When you can, please could you update air-flyafrica-zimbabwe-v1 (z7) to show that they finished operations in Oct 2015.
Also, Amaszonas Uruguay started operations on 06-2016 under Z7 (https://es.wikipedia.org/wiki/Amaszonas_Uruguay).
Thanks a lot,
Jane.

**Comment by denisarnaud** [comment]
Thanks for your contribution, Jane!

For the record:
1. [Línea Aérea Amaszonas](https://en.wikipedia.org/wiki/L%C3%ADnea_A%C3%A9rea_Amaszonas) (Z8/AZN) is a Bolivian airline founded in 1998
2. [BQB Líneas Aéreas](https://en.wikipedia.org/wiki/BQB_L%C3%ADneas_A%C3%A9reas) (5Q/BQB) was an airline based in Uruguay which ceased operations in 2015 when sold to Línea Aérea Amaszonas (Z8/AZN)
3. [Amaszonas Uruguay](https://en.wikipedia.org/wiki/Amaszonas_Uruguay) (Z7/AUZ) is a new airline, resulting from the take over by Línea Aérea Amaszonas (Z8/AZN) of BQB Líneas Aéreas (5Q/BQB)
4. [Paranair](https://en.wikipedia.org/wiki/Paranair) (ZP/AZP) is an airline, which was once part of Línea Aérea Amaszonas (Z8/AZN) and therefore branded as Amaszonas Paraguay. The rebranding into Paranair came after the separation with the latter
