### ISSUE TITLE
Missing location codes in optd_por_public.csv

### ISSUE THREAD

**Issue by vojnovski** [opentraveldata/opentraveldata#13]
While processing IATA prorating data, some three letter location codes are not found in optd_por_public.csv:

Present on http://www.iata.org/publications/Pages/code-search.aspx: 
**GEM** - Mongomo
**JJG** - Jaguaruna
**NBN** - Annobon
**RDP** - Durgapur

Google gave the rest:

Present in LH flights:
**KJR** - Karlsruhe Rail Station 
**KWQ** - Kassel-Wilhelmshöhe Rail Station
**MHJ** - Mannheim Rail Station
**QBB** - Thomastrasse Bus Station

LO flights:
**LKJ** - Lodz: Kaliska Bus Station

KL flights:
**QNQ** - Nijmegen Bus

9W flights:
**RUJ** - Riyadh Bus Station

**Comment by denisarnaud** [comment]
All those points of reference (POR) have been added.

Do not hesitate if you want more POR to be added.

Thanks!

**Comment by vojnovski** [comment]
Thanks!
