### ISSUE TITLE
Maldivian airport Funadhoo missing (IATA FND) 

### ISSUE THREAD

**Issue by pjburon** [opentraveldata/opentraveldata#131]
Hello,

The Maldivian new airport Funadhoo (IATA code FND) is missing in the file optd_por_public.csv.

Regards
Pierre-Jean Buron

**Comment by denisarnaud** [comment]
Thanks for the report!
For reference:
* Geonames: https://www.geonames.org/12104814
* Wikipedia: https://en.wikipedia.org/wiki/Funadhoo_Airport
* Maldivian airline: https://maldivian.aero/destinations/funadhoo.html

**Comment by denisarnaud** [comment]
[3 records have been added](https://github.com/opentraveldata/opentraveldata/commit/8d9ea05d87b45597f2f3522922d435e3d96314e1#diff-bd88c7fade35cd1067313b43ddc241f8R4719)
