### ISSUE TITLE
PAE associated city codes

### ISSUE THREAD

**Issue by alexprengere** [opentraveldata/opentraveldata#132]
Currently with the latest POR file:

- `SEA` airport has `city_code_list` `['SEA']`
- `PAE` airport has `city_code_list` `['PAE']`

But for [IATA](https://www.iata.org/publications/pages/code-search.aspx) the association is different for `PAE`, it relates to `SEA` city. Is there a reason for that discrepancy? Perhaps we could have both `PAE` and `SEA` in the `city_code_list`

**Comment by denisarnaud** [comment]
Good catch, thanks!
Since [Everett](https://www.geonames.org/5793933) (PAE) is [40+ kms away](https://transport-search.org/search/?q=pae+sea) from [Seattle](https://www.geonames.org/5809844) (SEA), I would rather keep both the cities in the list, as you suggest.
