### ISSUE TITLE
Entries to be added to the OPTD airlines file

### ISSUE THREAD

**Issue by deepak0000** [opentraveldata/opentraveldata#134]
Hello,

Please could you help me add entries for the following in your airlines file:

1. Update record for 3R with DVR ICAO code -> https://en.wikipedia.org/wiki/Divi_Divi_Air
2. Add entry for 5Z with KEM ICAO code -> https://en.wikipedia.org/wiki/CemAir
3. Update 4F with FDT ICAO code -> https://www.ch-aviation.com/portal/airline/FXK
4. And entry for Air Belgium (KF, ABB) -> https://en.wikipedia.org/wiki/Air_Belgium_(since_2016)
5. Add OPTD entry for Uni-top airlines -> https://en.wikipedia.org/wiki/Uni-Top_Airlines
6. Add entry for Air Philip (3P, APV) -> https://en.wikipedia.org/wiki/Air_Philip
7. Add entry for Regional Jet (EE, EST) -> https://en.wikipedia.org/wiki/Nordica_(airline)
8. Add entry for Al Naser Wings (NG, NAD) -> https://en.wikipedia.org/wiki/Al_Naser_Wings_Airlines
9. Add entry for Small Planet Airlines Cambodia (RD, LKH) -> https://en.wikipedia.org/wiki/Small_Planet_Airlines_(Cambodia)
10. Update ICAO code for LC Peru (W4, LCB) -> https://en.wikipedia.org/wiki/LC_Per%C3%BA
11. Update entry for Manta Air (MA, MAV) -> https://en.wikipedia.org/wiki/Manta_Air
12. Entry for Great Dane airlines (DW, GDE) -> https://en.wikipedia.org/wiki/Great_Dane_Airlines
13. Entry for Albatros airlines (G2, GAL) -> https://en.wikipedia.org/wiki/Albatros_Airlines
14. Entry for Real Tonga (R4, RLT) -> https://en.wikipedia.org/wiki/Real_Tonga

Happy holidays and best regards,
Deepak

**Comment by denisarnaud** [comment]
All the items in the list (and many more) have been handled. Many thanks for your contribution!
