### ISSUE TITLE
BAX airport with wrong timezone

### ISSUE THREAD

**Issue by MrMey** [opentraveldata/opentraveldata#138]
Hello,
Thanks again for the job you've done.

I came across the issue of **BAX** airport (**Barnaul** city in Russia).
It is linked to **Asia/Omsk (UTC+6)** in the `optd_por_public.csv` but in fact I think it is currently **Asia/Novosibirsk (UTC+7)**.
See : https://www.timeanddate.com/time/zone/russia/barnaul

Could you kindly have a look on this case ? Thanks.

Bests 
Romain

**Comment by denisarnaud** [comment]
Thanks for your contribution, Romain!

The timezone was indeed wrong on Geonames, and I just fixed it: https://www.geonames.org/6300983
The update will appear in the new Geonames data dump tomorrow, and will be integrated into OPTD afterwards.

I would be very curious (and glad to know) how you came up spotting that error, if you can share of course.

As a matter of fact, if you have some ideas on adding data quality monitoring tests, do not hesitate to contribute to https://github.com/opentraveldata/quality-assurance/tree/master/checkers

Thanks!

Cheers

Denis

**Comment by MrMey** [comment]
Hello Denis,
Thanks for your fix, and I am glad to report such issues. 

In this specific case, I was computing flying time between BAX and OVB (which is really close but correctly linked to its timezone Asia/Novosibirsk) and I got negative elapsed flying time.

It is first time I report the issue but I tend to spot some inconsistencies quickly (mostly inconsistencies with other IATA-based source like this one : [Issue 132](https://github.com/opentraveldata/opentraveldata/issues/132). If it was right way and right place to report issues, I'll be glad to go on.

Indeed, it is better to spot these before hand, I will have a look on the tests and try to think about additional checks.

Bests
Romain

**Comment by denisarnaud** [comment]
Yes, reporting issues like for #132 is already very good!

Any "homework" you could do (e.g., collecting information about the incriminated POR, pointing to references/sources, hinting to potential solutions, if possible with source code) would be appreciated.

And you are of course very welcome to the team of the [organization (OPTD)](https://github.com/opentraveldata), if you like!

Cheers

D
