### ISSUE TITLE
Seas of the world

### ISSUE THREAD

**Issue by JohanGahnstrom** [opentraveldata/opentraveldata#140]
Hi, 
This is a suggested addition. IHO has a specification "Limits of Oceans and Seas" (1953) https://iho.int/uploads/user/pubs/standards/s-23/S-23_Ed3_1953_EN.pdf. Attemps has been made to update this publication a number of times but there issues with a number of sea areas that cannot be resolved. Hence, the 1953 is still valid. There is an implementation on all the coordinates available here:  https://sourceforge.net/projects/openseamap/files/jseas.zip
I thought it might be useful for this project to make available names of the seas as a part of it. This data is mainly focuse on airlines, but could be extended with sea/port information especially since UNLOCODE is used in the shipping world as well.

**Comment by denisarnaud** [comment]
Thanks Johan!

That is a good idea, which would however require significant integration work, IMHO. I have added that information in a new [`data/seas-of-the-world` dedicated folder](https://github.com/opentraveldata/opentraveldata/tree/master/data/seas-of-the-world).
