### ISSUE TITLE
New currency VES (replacing VEF) in Venezuela

### ISSUE THREAD

**Issue by MrMey** [opentraveldata/opentraveldata#148]
Hello Denis,
After looking at [Geonames ](https://www.geonames.org/countries/VE/venezuela.html)and [Wikipedia](https://en.wikipedia.org/wiki/Venezuelan_bol%C3%ADvar), I bumped into the fact that Venezuela changed its currency in 2018 (VES).
After a look in the optd_por_public.csv, it seems Venezuela still have the old currency (VEF).

Romain
Bests

**Comment by denisarnaud** [comment]
Thanks Romain, good catch!

The currency codes are retrieved by OPTD from the [`opentraveldata/optd_countries.csv` file](https://github.com/opentraveldata/opentraveldata/blob/master/opentraveldata/optd_countries.csv#L240).

That file itself is being derived manually (every so often) thanks to the [`tools/make_optd_country.sh` Shell script](https://github.com/opentraveldata/opentraveldata/blob/master/tools/make_optd_country.sh) (and associated [`tools/make_optd_country.awk` AWK script](https://github.com/opentraveldata/opentraveldata/blob/master/tools/make_optd_country.awk)).

So, I just re-ran it, thanks to you (!), and updated the OPTD POR files.

So, we had a few other updates of currencies, for instance for:
* Belarus (BY): from BYR to BYN
* Mauritania (MR): from MRO to MRU
* Venezuela (VE): from VEF to VES

38d5fbeafefa9dcad97933254167812bf00346b7 brings all those changes.

Do not hesitate to remind me/us in the future when the country details have changed.

**Comment by MrMey** [comment]
Hello, 
I think the currency of San Tome and Principe is STN and not STD as in the [optd_countries.csv](https://github.com/opentraveldata/opentraveldata/blob/master/opentraveldata/optd_countries.csv#L240).

Apparently it did change in 2018 (see [Wikipedia](https://en.wikipedia.org/wiki/S%C3%A3o_Tom%C3%A9_and_Pr%C3%ADncipe_dobra))

In fact I used data from the organization that maintains the currency standard ISO4217. They publish on their website [two documents](https://www.currency-iso.org/en/home/tables/table-a1.html) (xls and xml) with the currencies per country (+some additional currencies). Looking at the website activity, it seems they keep it up-to-date. Maybe the [xml](https://www.currency-iso.org/dam/downloads/lists/list_one.xml) version could be used to validate the currencies. 

Their policy states these documents are free-to-use:

> ISO allows free-of-charge use of its country, currency and language codes from ISO 3166, ISO 4217 and ISO 639, respectively.

Note that it would require a small matching step because the country name they use do not match perfectly yours (for example the stop words position may change like `Bahamas` vs `BAHAMAS (THE)`).
