### ISSUE TITLE
airports without IATA code missing in POR file

### ISSUE THREAD

**Issue by wsteitz** [opentraveldata/opentraveldata#15]
many airports don't have an IATA code, but just an ICAO one. Usually, these are very small airports without any scheduled flights. But some of them do have regular flights and it would be nice to have them in our POR file. 

An example is [Beringin Airport](https://en.wikipedia.org/wiki/Beringin_Airport). The airport actually exists in [geonames](http://www.geonames.org/8531905/beringin-airport.html), but we don't seem to pick it up from there.

**Comment by denisarnaud** [comment]
The airports having an ICAO code but no IATA code can now be added to OPTD. We start with the reported (formerly) missing one, which has be added: http://search-travel.org/search/?q=waom&z=14

For other such airports, just add them in the [opentraveldata/optd_por_best_known_so_far.csv file](http://github.com/opentraveldata/opentraveldata/blob/master/opentraveldata/optd_por_best_known_so_far.csv), with ZZZ as IATA code, and the corresponding Geonames ID ([8531905](http://geonames.org/8531905) here).
