### ISSUE TITLE
Change IATA code from TSE to NQZ

### ISSUE THREAD

**Issue by mlazzarou** [opentraveldata/opentraveldata#152]
Hello! We noticed that the IATA code for the airport Nursultan Nazarbayev International Airport was "TSE" but now it has been changed to "NQZ", as you can see below : https://en.wikipedia.org/wiki/Nursultan_Nazarbayev_International_Airport
This caused our code to fail, can you please update it ? 
Many Thanks!
Maroua

**Comment by denisarnaud** [comment]
Thanks for your contribution!

Apparently, the IATA code for that airport is still TSE:
* https://www.iata.org/en/publications/directories/code-search/?airport.search=tse yields the airport, as expected
* https://www.iata.org/en/publications/directories/code-search/?airport.search=nqz yields no result

And the [Wikipedia page](https://en.wikipedia.org/wiki/Nursultan_Nazarbayev_International_Airport), no mention is made about any change in the IATA code. The name of the airport changed many times in its history, but not the IATA code itself.

Did I miss something?

**Comment by denisarnaud** [comment]
Ok. For reference, on the [Wikipedia history page](https://en.wikipedia.org/w/index.php?title=Nursultan_Nazarbayev_International_Airport&offset=20200530112655%7C959745254&action=history), it is stated:
> NURSULTAN NAZARBAYEV AIRPORT CHANGED ITS CODE According to the special notification of the International Air Transport Association (IATA) dated April 6, 2020, the final official decision was made to change the current three-letter code of the Nursultan Nazarbayev International Airport from TSE to NQZ, Strategy2050.kz reports with reference to the Civil Aviation Committee

And [a source](http://en.egemen.kz/article/228246-kazakh-capital-airport-code-changed-to-nqz)  is even given.

It is too late for the change to appear today, but it should appear tomorrow (12 June 2020).

Thanks!

Kind regards

Denis

**Comment by denisarnaud** [comment]
Thanks to both of you!

The data sets have been updated.
Just wondering what will happen when the leader will change, whether they will rename the city and airport again :)

**Comment by bezineb5** [comment]
Thanks to you!
Yes, and actually the wikipedia history seems to be home of heated debate!
