### ISSUE TITLE
Please add an entry for UR in the optd_airlines file

### ISSUE THREAD

**Issue by deepak0000** [opentraveldata/opentraveldata#153]
Hello,

I notice that in the optd_airlines file that UR is still associated with UTair Express, which ceased operations on 10th June, 2015.
(ref - https://en.wikipedia.org/wiki/UTair_Express)
UR is now associated with Uganda Airlines, (ref - https://en.wikipedia.org/wiki/Uganda_Airlines) which commenced operations on 28th August, 2019 - please could you invalidate the existing entry and add a new one for Uganda Airlines?

Best,
Deepak

**Comment by denisarnaud** [comment]
For reference, https://en.wikipedia.org/wiki/Uganda_Airlines_(1976%E2%80%932001) points to the former Uganda Airlines, which the new one is a revival of.
