### ISSUE TITLE
Please add 5W - Wizz Air Abu Dhabi to the optd_airlines.csv file

### ISSUE THREAD

**Issue by deepak0000** [opentraveldata/opentraveldata#157]
Hello,

Please could you add 5W (ICAO code - WAZ) - Wizz Air Abu Dhabi to the optd_airlines.csv file?
Wiki link for reference - https://en.wikipedia.org/wiki/Wizz_Air_Abu_Dhabi

Currently, 5W is assigned WESTbahn Management GmbH.

Best,
Deepak

**Comment by deepak0000** [comment]
Hello @denisarnaud!
Please could you help us with this entry?
Best regards,
Deepak

**Comment by denisarnaud** [comment]
Sure!
Will try to have a look at it this week.
Thanks for your suggestion!

**Comment by denisarnaud** [comment]
Thanks for your contribution, @deepak0000 !
