### ISSUE TITLE
Missing IATA code DBR

### ISSUE THREAD

**Issue by MrMey** [opentraveldata/opentraveldata#158]
Hello Denis,
I spotted the Airport DBR (India) that is in IATA data but not in the optd_por_public_all.csv
![image](https://user-images.githubusercontent.com/22343284/110775914-c4314780-825f-11eb-992c-5dadeda57086.png)

I couldn't find any recent change in the news that could explain opentraveldata would not have the data. 

Bests,
Romain

**Comment by denisarnaud** [comment]
Thanks for your contribution, Romain!

For reference:
* [Darbhanga Airport on Geonames](https://www.geonames.org/12217912/darbhanga-airport.html)
* [Darbhanga Airport on Wikipedia](https://en.wikipedia.org/wiki/Darbhanga_Airport)
* [Darbhanga city on Geonames](https://en.wikipedia.org/wiki/Darbhanga)
* [Darbhanga city on Wikipedia](https://en.wikipedia.org/wiki/Bihar)
* [Bihar state on Geonames](https://www.geonames.org/1275715/state-of-bihar.html)
* [Bihar state on Wikipedia](https://en.wikipedia.org/wiki/Bihar)

**Comment by MrMey** [comment]
always a pleasure
thanks for the fix
