### ISSUE TITLE
Why the shape of  data/IATA/archives/iata_airport_list_YYYYMMDD.csv has changed?

### ISSUE THREAD

**Issue by wuarmin** [opentraveldata/opentraveldata#165]
Hello,

I noticed, that the shape of iata_airport_list_YYYYMMDD.csv-file has changed on  Jun 24 2021 from 
`city_code^city_name^state_code^country_code^tz_code^stv^por_code^por_name^loc_id^loc_type`
to 
`city_name^por_code^por_name`

What's the reason? I need a list of IATA-Airport-Codes. Is the new resource:

https://ourairports.com/data/

Thanks and best regards

**Comment by denisarnaud** [comment]
Thanks for your comment!

Could you contact me in a private message?
