### ISSUE TITLE
multiple airports with the same IATA code active at the same time

### ISSUE THREAD

**Issue by wsteitz** [opentraveldata/opentraveldata#17]
Sometimes IATA airport codes are reused. But at any point in time, the IATA codes of active airports should be unique. Looking at optd_por_public.csv, this is currently not the case. The date_from/date_to dates seem to be incomplete.

These IATA codes can be detected with a python script: https://gist.github.com/wsteitz/0905c749b6b811e1df75

The output of the script:
MZA 1900-01-01 to 2012-09-01 and 1900-01-01 to 2999-12-31
YGS 1900-01-01 to 2013-09-01 and 1900-01-01 to 2013-09-01
MHC 1900-01-01 to 2012-01-01 and 1900-01-01 to 2999-12-31
NAT 1900-01-01 to 2014-06-01 and 1900-01-01 to 2999-12-31
SHO 1900-01-01 to 2012-12-14 and 1900-01-01 to 2999-12-31

**Comment by denisarnaud** [comment]
The Python script has been (amended and) added to the [Quality Assurance (QA) tests](http://github.com/service-delivery-quality/quality-assurance/blob/master/samples/opentraveldata/check-por-duplicate-iata.py) of the [Service Delivery Quality (SDQ) project](http://github.com/service-delivery-quality).
Current output of that check:
```json
{'geonames_id': '5960660', 'location_type': 'CA', 'date_from': '1900-01-01', 'date_until': '2013-09-01', 'env_id': '1', 'country_code': 'CA', 'por_code': 'YGS'}
{'geonames_id': '11001159', 'location_type': 'A', 'date_from': '1900-01-01', 'date_until': '2999-12-31', 'env_id': '', 'country_code': 'PE', 'por_code': 'MZA'}
{'geonames_id': '3406959', 'location_type': 'A', 'date_from': '1900-01-01', 'date_until': '2014-06-01', 'env_id': '1', 'country_code': 'BR', 'por_code': 'NAT'}
{'geonames_id': '8521372', 'location_type': 'A', 'date_from': '1900-01-01', 'date_until': '2999-12-31', 'env_id': '', 'country_code': 'SZ', 'por_code': 'SHO'}
{'geonames_id': '8410843', 'location_type': 'A', 'date_from': '1900-01-01', 'date_until': '2999-12-31', 'env_id': '', 'country_code': 'CL', 'por_code': 'MHC'}
```

**Comment by wsteitz** [comment]
no more overlaps!
