### ISSUE TITLE
Please add RMZ - Tobolsk Remezov Airport to the optd_por_public.csv file

### ISSUE THREAD

**Issue by deepak0000** [opentraveldata/opentraveldata#171]
Hello,

Please could you add RMZ (Tobolsk Remezov Airport) to the optd_por_public file?
Looks like there's already an entry for Tobolsk (TOX), but I don't know if that is correct.

Wiki link for reference - https://en.wikipedia.org/wiki/Tobolsk_Remezov_Airport

Best,
Deepak

**Comment by alexprengere** [comment]
Looking at the map, this looks like a new airport that was built fairly close to the other one TOX.
I created a [new entry](https://www.geonames.org/12402302/tobolsk-remezov-airport.html) in GeoNames for this.
Tomorrow, once the new data will be available in GeoNames dumps, I will add the entry to opentraveldata reference file.
