### ISSUE TITLE
IATA code reassignment - Nice Helicopteres and Starlux

### ISSUE THREAD

**Issue by thepermanenturl** [opentraveldata/opentraveldata#185]
JX is labeled as “Nice Helicopteres” but should be Starlux Airlines (according to IATA)

https://en.wikipedia.org/wiki/Starlux_Airlines

https://www.routesonline.com/airlines/4110/nice-helicopteres/

**Comment by thepermanenturl** [comment]
Hi,
Created this PR for correcting this issue. 
https://github.com/opentraveldata/opentraveldata/pull/209

**Comment by alexprengere** [comment]
Thanks! I merged it and will regenerate the final output.
