### ISSUE TITLE
Time zone updates for Chile

### ISSUE THREAD

**Issue by mtang-hash** [opentraveldata/opentraveldata#193]
Hi, there has been a recent update for the timezone in Chile: https://techcommunity.microsoft.com/t5/daylight-saving-time-time-zone/interim-guidance-on-2022-time-zone-updates-for-chile/ba-p/3598290 

Could you maybe take a look into it? Thanks a lot!

**Comment by alexprengere** [comment]
As far as I understand, this kind of changes will impact the Olson database, not opentraveldata.
There are places in opentraveldata where we have, for each point of reference, an associated timezone.
For example `SCL` airport has `America/Santiago`, and this will not change. What will change is the underlying meaning of `America/Santiago` when computing time differences. This is the work of third party libraries like `pytz` or `zoneinfo` (in Python), that rely themselves on `tzdata`. So, unless I missed something, the changes will have to happen there.

**Comment by alexprengere** [comment]
After double-checking, latest versions of tzdata include the updates for Chile. So you just need to update the tzdata systems package.
