### ISSUE TITLE
Addition of Arajet and removal of Asian Air

### ISSUE THREAD

**Issue by thepermanenturl** [opentraveldata/opentraveldata#197]
The IATA code for Arajet is DM in 
https://www.iata.org/en/publications/directories/code-search/?airline.search=DM

Please consider changing 
https://github.com/opentraveldata/opentraveldata/blob/4b4e44b9c2dd2154cbd7f3ea2f9dd43cf036a201/opentraveldata/optd_airlines_websites.csv#L886

and 

https://github.com/opentraveldata/opentraveldata/blob/52a571ecd1c2cf325746134957eded6d43529048/opentraveldata/optd_airlines.csv#L1279

There may be other corrections I am not aware of.

DM was previously attached to Asian Air but that seems to have changed.

**Comment by alexprengere** [comment]
Thanks! Would you be willing to open a PR? For the record only the file "optd_airline_best_known_so_far.csv" should be changed, the rest is automatically generated from that.

As an example you can see [this](https://github.com/opentraveldata/opentraveldata/pull/196/files). Once the PR is merged I will generate all final files.

**Comment by thepermanenturl** [comment]
Yes sure. I'll make the change now.

**Comment by thepermanenturl** [comment]
Opened PR 
https://github.com/opentraveldata/opentraveldata/pull/198
Thank you

**Comment by thepermanenturl** [comment]
PR merged. Thank you for your speedy response :)
