### ISSUE TITLE
IATA OPTD airline code mismatch

### ISSUE THREAD

**Issue by thepermanenturl** [opentraveldata/opentraveldata#199]
Two have differing iata codes and their optd entries

Y2
IATA: Air Century, S.A.
optd : Ygnus

4J
IATA: United Caribbean Airlines BV d.b.a.JetAir Caribbean
optd : FlyAdams

**Comment by thepermanenturl** [comment]
Created PR https://github.com/opentraveldata/opentraveldata/pull/200

Couldnt find the validity dates :( so put todays.

**Comment by alexprengere** [comment]
PR #200 is now merged, closing this.
