### ISSUE TITLE
Duplicate EAP entries

### ISSUE THREAD

**Issue by bmomjian** [opentraveldata/opentraveldata#205]
In the optd_por_public.csv file, is there a reason there are two iata_code entries for "EAP" (EuroAirport Basel–Mulhouse–Freiburg) that are both have blank date_until values?  This is the only such case in the file.

**Comment by alexprengere** [comment]
Indeed this filters two lines:

```
cat optd_por_public.csv  |grep '^EAP'
```

But this is not the only case, every IATA code that refers _both_ to an airport and a city (like NCE), will have one line for the airport, and one line for the city.
Note that EAP is a strange case for [many other reasons](https://en.wikipedia.org/wiki/EuroAirport_Basel_Mulhouse_Freiburg), for example it has multiple IATA codes.

**Comment by bmomjian** [comment]
Well both "EAP" lines have 'fcode's of 'AIRP':

`awk -F'^' '$1 == "EAP" && $15 == "" {print $12}' optd_por_public.csv`

How do I know which is the airport and which is the city code?  The two NCE lines have fcodes of "AIRP"" and "PPLA2" so it is easy to know which one is the airport.

Also, where is the meaning of the fcodes documented?  Thanks.  Also, optd_por_public.csv seems more like a caret-delimited file rather than a CSV file as the file extension suggests.

**Comment by alexprengere** [comment]
There is a `location_type` column (at index 41) that can contain letters, for example:
* C for city 
* A for airport
* CA for both
* R for railway
* B for bus
* H for heliport

`fcodes` are the feature codes [coming from GeoNames](https://www.geonames.org/export/codes.html), which is one of the input data sources of OpenTravelData, so we keep that information in the final file.

**Comment by bmomjian** [comment]
Uh, sorry but I am still confused.  If I go only by the $41 field, I see:
```
awk -F'^' '$1 == "ACV" {print $41}' optd_por_public.csv
CA
CA
```

which makes it hard to figure out which line is the city and which one is the airport, and for EAP I see:
```
awk -F'^' '$1 == "EAP" {print $41}' optd_por_public.csv
GES
GES
```
which are also identical and not listed as valid letters in your chart above.

**Comment by alexprengere** [comment]
I used 41 from the Python code where indices start at 0 😢 With awk/cut, this would be 42:

```bash
$ awk -F'^' '$1 == "ACV" {print $42}' optd_por_public.csv
A
C
$ awk -F'^' '$1 == "EAP" {print $42}' optd_por_public.csv
A
C
```

**Comment by bmomjian** [comment]
Yes, that works, thanks.  I think I am good now.  I will open a new case on a question about DHA.
