### ISSUE TITLE
DHA is listed as a heliport

### ISSUE THREAD

**Issue by bmomjian** [opentraveldata/opentraveldata#206]
I noticed that IATA code DHA, King Abdulaziz Air Base, Dhahran, is listed with a location code (42nd field) of "H"/heliport.  However, that seems more like a military airport:

          https://en.wikipedia.org/wiki/King_Abdulaziz_Air_Base

**Comment by alexprengere** [comment]
It looks like you are correct, the [GeoNames entry](https://www.geonames.org/392652/king-abdulaziz-air-base.html) also lists this as an airbase.
I fixed it in https://github.com/opentraveldata/opentraveldata/commit/8deb81fd60c72f3c1e1cfe15d7c3ff6f72e61a68, thanks!
