### ISSUE TITLE
Airport size in optd_por_public.csv

### ISSUE THREAD

**Issue by bmomjian** [opentraveldata/opentraveldata#207]
Is there any indication of an airport's size in optd_por_public.csv?

**Comment by alexprengere** [comment]
In the [main output file](https://github.com/opentraveldata/opentraveldata/blob/master/opentraveldata/optd_por_public.csv), there are 2 fields that can help you:
* page_rank: when generating that file we build the graph of flight schedules, then we derive the [pagerank](https://fr.wikipedia.org/wiki/PageRank) of the nodes from there, this is a direct measure of the airport importance in the schedules
* population, which makes sense for IATA codes that are cities

**Comment by bmomjian** [comment]
That is very helpful, thank you.  I was using a different CSV file to select just the large airports, and then joining it with yours.  With this information, I can use just your file.  I also appreciate you update your content promptly.
