### ISSUE TITLE
Identify rail IATA codes

### ISSUE THREAD

**Issue by pgrandjean** [opentraveldata/opentraveldata#218]
Would it be possible to include and identify IATA codes that are actually rail segments? For instance, airline 9B for AccessRail.

**Comment by alexprengere** [comment]
As long as they are part of the IATA standard, sure. It looks like this one is already in the [airline reference file](https://github.com/opentraveldata/opentraveldata/blob/89d4465610943e9cbf4e76c1417a503ec92ed98b/opentraveldata/optd_airline_best_known_so_far.csv#L1148) though.
