### ISSUE TITLE
Unknown timezones in latest optd_por_public

### ISSUE THREAD

**Issue by alexprengere** [opentraveldata/opentraveldata#22]
I checked the latest optd_por_public and we have a good number of por with invalid timezones. I ran the same script as last time to try to find relevant existing timezones for those:
```
KXD with tz "Europe/Russia" matches tz "Asia/Yekaterinburg" (dist 156.9km, "Kondinskoye RU" -> "Uray")
DUQ with tz "America/Canada" matches tz "America/Vancouver" (dist 0.2km, "Duncan BC CA" -> "Duncan")
RJM with tz "Asia/Indonesia" matches tz "Asia/Jayapura" (dist 74.3km, "Waisai ID Marinda" -> "Sorong")
NSA with tz "America/Brazil" matches tz "America/Fortaleza" (dist 4.4km, "Natal" -> "Natal")
NGF with tz "America/USA" matches tz "Pacific/Honolulu" (dist 5.7km, "Kaneohe Bay HI US Mcas" -> "Kailua")
HDQ with tz "" matches tz "Africa/Accra" (dist 577.0km, "Headquarters ZZ" -> "Takoradi")
LUF with tz "America/USA" matches tz "America/Phoenix" (dist 10.2km, "Phoenix" -> "El Mirage")
AXI with tz "Europe/Spain" matches tz "Europe/Madrid" (dist 0.8km, "Algeciras" -> "Algeciras")
TNQ with tz "Pacific/Kiribati" matches tz "Pacific/Honolulu" (dist 1765.1km, "Teraina KI" -> "Hilo")
JBU with tz "Europe/Spain" matches tz "Europe/Madrid" (dist 1.2km, "Santiago de Compostela" -> "Santiago de Compostela")
RAT with tz "Europe/Russia" matches tz "Asia/Magadan" (dist 287.4km, "Raduzhny RU" -> "Magadan")
EVO with tz "Europe/Spain" matches tz "Europe/Madrid" (dist 1.7km, "Estepona ES Bus Station" -> "Estepona")
SWM with tz "America/Brazil" matches tz "America/Sao_Paulo" (dist 224.8km, "Alto Boa Vista MT BR Suia Miss" -> "São Miguel do Araguaia")
UIZ with tz "America/USA" matches tz "America/New_York" (dist 1.4km, "Utica MI US Berz Macomb" -> "Utica")
TQQ with tz "Asia/Indonesia" matches tz "Asia/Makassar" (dist 180.5km, "Tomia ID Maranggo" -> "Katabu")
FOP with tz "America/USA" matches tz "America/New_York" (dist 8.5km, "Forest Park GA US Morris Aaf" -> "Evans")
GHK with tz "America/Canada" matches tz "America/Yellowknife" (dist 283.3km, "Kennedy Lake NT CA Gahcho Kue" -> "Yellowknife")
NNN with tz "" matches tz "Africa/Accra" (dist 577.0km, "Pseudo Message Dep ZZ" -> "Takoradi")
HKP with tz "America/USA" matches tz "Pacific/Honolulu" (dist 199.5km, "Kaanapali Maui HI US" -> "Kailua")
VBR with tz "Europe/Russia" matches tz "Europe/Moscow" (dist 0.9km, "Vyborg RU Railway Station" -> "Vyborg")
RVH with tz "Europe/Russia" matches tz "Europe/Moscow" (dist 5.4km, "Saint Petersburg" -> "Vsevolozhsk")
VVV with tz "" matches tz "Africa/Accra" (dist 577.0km, "Pseudo Message Arr ZZ" -> "Takoradi")
SZQ with tz "America/Argentina" matches tz "America/Argentina/Cordoba" (dist 3.7km, "Saenz Pena BA AR" -> "Presidencia Roque Sáenz Peña")
ZMD with tz "America/Brazil" matches tz "America/Rio_Branco" (dist 0.7km, "Sena Madureira AC BR" -> "Sena Madureira")
PZS with tz "America/Chili" matches tz "America/Santiago" (dist 4.3km, "Temuco" -> "Temuco")
BBE with tz "America/Argentina" matches tz "America/Montevideo" (dist 6.4km, "Buenos Aires" -> "Maldonado")
SMT with tz "America/Brazil" matches tz "America/Cuiaba" (dist 70.1km, "Sorriso MT BR" -> "Sinop")
ZUF with tz "Pacific/New_Zealand" matches tz "Pacific/Auckland" (dist 5.4km, "Mystery Explorer NZ" -> "Mangere")
GVW with tz "America/USA" matches tz "America/Chicago" (dist 0.3km, "Grandview MO US Richards Gebau" -> "Grandview")
ENZ with tz "Pacific/New_Zealand" matches tz "Pacific/Auckland" (dist 5.4km, "Mystery Break NZ Mystery Break" -> "Mangere")
CAT with tz "Atlantic/Portugal" matches tz "Europe/Lisbon" (dist 3.6km, "Cascais PT Tires" -> "São Domingos de Rana")
IAT with tz "" matches tz "America/Los_Angeles" (dist 160.2km, "Iata Traffic Serv ZZ" -> "Lompoc")
YWO with tz "America/Canada" matches tz "America/Yellowknife" (dist 397.4km, "Lupin NT CA Lupin" -> "Yellowknife")
```

**Comment by denisarnaud** [comment]
Thanks!

Could you please provide a pointer to your script?

**Comment by alexprengere** [comment]
For more context see opentraveldata/optd#31, the actual script is [here](https://gist.github.com/alexprengere/7a8a35c691fad5f170d8).

**Comment by denisarnaud** [comment]
Added a file, contributed by @aseredyn: 
[optd_city_timezone-2016-05-02-AS.xlsx](https://github.com/opentraveldata/opentraveldata/files/275152/optd_city_timezone-2016-05-02-AS.xlsx)

Some context:
* There are cases of different time zone references for the same city. For instance, Odessa airport (ODS, “A”) is in a different time-zone than Odessa city (ODS, “C”).
* There are more cases, referenced in the above Excel sheet (there are only cases with env_id=="" && !is.na(page_rank) && !is.na(gmt_offset)).
* There are plenty other cases, where some bus station or outdated airport in a given city has some other (or missing) time-zone info than the main one in the city. Those are ignored in this quick check.
* In some cases, the time-zone label is different (e.g., "A, VSA, America/Merida" vs. "C, VSA, America/Mexico_City"). But, in some other cases, the time-zone (and hence GMT offset) is different (like in the case of ODS). In the Excel, those are marked in the “diff_offset” column.
* The numbers of scheduled flights of full 2015 are also provided, so as to sort by the most relevant ones.

**Comment by tadhgpearson** [comment]
+1 for this, it's breaking our timezone import

**Comment by denisarnaud** [comment]
There are still a lot of POR with time-zone issues. Almost all of them are now reported in a new CSV file: [opentraveldata/optd_por_tz_wrong.csv](https://github.com/opentraveldata/opentraveldata/blob/master/opentraveldata/optd_por_tz_wrong.csv). However, none of them appear in flight schedules (their PageRank values are null); so, if you filter the null-PageRank POR, you shouldn't have any issue any more.

Those POR correspond to entries appearing in reference data, but not in OpenTravelData.
1. Some of the POR are missing, and should be added to OpenTravelData. For that, add the corresponding entries in [opentraveldata/optd_por_best_known_so_far.csv](https://github.com/opentraveldata/opentraveldata/blob/master/opentraveldata/optd_por_best_known_so_far.csv).
2. Some others are invalid, and must be filtered out. For that, just add entries in [opentraveldata/optd_por_ref_exceptions.csv](https://github.com/opentraveldata/opentraveldata/blob/master/opentraveldata/optd_por_ref_exceptions.csv).

**Comment by tadhgpearson** [comment]
Thanks for the clarification Denis. However, it's still not clear to me - do all cities / airports in the optd_por_public file require a timezone? Should we be adding those that don't have a timezone to the exceptions list so that they are not included in the output?

**Comment by denisarnaud** [comment]
There is no such thing as a file "requiring" a valid time-zone; whereas you, as a user, may require a valid time-zone. If that is the case (and I fully understand that it would be the case!), then a quick work around is to filter out the records having no PageRank value.
On the longer term, we should add to Geonames the missing POR. Then, once the POR are in Geonames, the time-zone will automatically be valid.

**Comment by denisarnaud** [comment]
All the time-zone errors have been fixed.
See also [opentraveldata/optd_por_tz_wrong.csv](https://github.com/opentraveldata/opentraveldata/blob/master/opentraveldata/optd_por_tz_wrong.csv).

**Comment by alexprengere** [comment]
I confirm that all timezones are now valid! Thanks Denis!
