### ISSUE TITLE
Airport corrections

### ISSUE THREAD

**Issue by sahilkulria002** [opentraveldata/opentraveldata#238]
[
    {
        "iata": "QXD",
        "validity end": "2013-12-31",
        "corrected validity end": "NA",
    },
    {
        "iata": "JSO",
        "validity start": "2023-01-01",
        "corrected validity start": "2022-04-01"
    },
    {
        "iata": "RVI",
        "validity end": "2018-03-01",
        "corrected validity end": "2018-06-01",
    },
    {
        "iata": "RQA",
        "validity start": "2018-07-01",
        "corrected validity start": "2018-03-29",
    },
    {
        "iata": "FMV",
        "": "add this as airport also, it is added a city"
    },
    {
        "iata": "LGZ",
        "validity start": "2023-01-12",
        "corrected validity start": "2022-12-01",
    },
    {
        "iata": "KCY",
        "": "add this completely"
    },
    {
        "iata": "HHP",
        "": "add this as airport also, it is added a city"
    },
    {
        "iata": "XZM",
        "": "add this as airport also, it is added a city"
    }
]

**Comment by alexprengere** [comment]
Thanks! A few remarks.

- [ ] QXD indeed has an validity back in 2013, which was actually correct, as it used to refer to Cachoeiro de Itapemirim. But indeed, the QXD IATA code has been re-attributed to [Quixada airport](https://en.wikipedia.org/wiki/Quixad%C3%A1_Airport), which is really new, I will add it soon.
- [x] JSO: OK
- [x] RVI: OK
- [x] RQA: OK
- [ ] FMV: this one is actually a "Montevideo Fluvial Bus Station" that is tied to Montevideo city (MVD), so IMO we should not ass FMV as a city
- [x] LGZ: OK, though the [wikipedia page](https://en.wikipedia.org/wiki/Shannan_Longzi_Airport) mentions the first flights on 2023-01-12
- [x] KCY: this one is already added, though very recently
- [ ] HHP: this one is an heliport that is tied to HKG as a city code, no need to add it as a city
- [ ] XZM: this one is a ferry terminal that is tied to MFM as a city code, no need to add it as a city

Apart from checking wikipedia, I do not have a very precise way to check validity dates, so I am going to trust your recommendations. May I ask how you did you compute those? Using what data sources?

**Comment by alexprengere** [comment]
I added QXD which was quite easy to locate. As all points have been addressed, I will close.
