### ISSUE TITLE
Feature Request: Include currency codes

### ISSUE THREAD

**Issue by tadhgpearson** [opentraveldata/opentraveldata#30]
It would be very useful to include the ISO 4217 currency code in either optd_country_region_info.csv or  	optd_por_public.csv

Currently we use this data to back sandbox.amadeus.com, and being able to display the currency of the city is a popular request. The use case is obvious: when the developer identifies the traveler's nearest relevant airport, they want to be able to display the results of flight/car/hotel searches in the traveler's currency. As a result, they need that currency data when they look up the location.

In the sandbox, we provide this in the output, merging it with a [simple gist we found](https://gist.github.com/HarishChaudhari/4680482) when the data is uploaded to our service.  But we would much rather it comes from Open Travel Data ;)

I can see you have some currency related elements in here already - https://github.com/opentraveldata/opentraveldata/tree/master/data/currency/ccy - but it doesn't seem to be used.

Could we include the currency in one or more of the maintained output data files?

**Comment by alexprengere** [comment]
Hi,
Not really answering your question, but I have had the same use case and I used the [GeoNames data](http://download.geonames.org/export/dump/countryInfo.txt) to map a country code to a currency code (and obviously opentraveldata to map a point of interest to a country code). It is already included in GeoBases with [`data=countries`](https://github.com/opentraveldata/geobases/blob/public/GeoBases/DataSources/Sources.yaml#L28).

**Comment by tadhgpearson** [comment]
Thanks Alex. That looks a bit more 'official' than what I used :)
So, this sounds like a common use case, why don't be add it to the output data? Do you think it's better to map it as part of the countries file, or also in the POR file?

**Comment by alexprengere** [comment]
Since the use case is pretty common, indeed we could add it to the POR file, to be able to directly map any airport to its currency, the same way we already do for country names, continents, etc..

**Comment by tadhgpearson** [comment]
Woohoo!
