### ISSUE TITLE
How is page_rank calculated (and why does CFN have a page rank but LDY does not)?

### ISSUE THREAD

**Issue by tadhgpearson** [opentraveldata/opentraveldata#33]
We're working to replace our old ORI number of movements data with page rank in our [nearest relevant airport API](https://sandbox.amadeus.com/travel-innovation-sandbox/apis/get/airports/nearest-relevant)

In general, we see improved results, but we also see some unwelcome regressions. 

For example, I come from [Letterkenny](https://tools.wmflabs.org/geohack/geohack.php?pagename=Letterkenny&params=54.9566_N_-7.7203_E_dim:100000_region:IE). My local nearby airports would be DUB, LDY, CFN, BFS, BHD. Today, the API returns these airports, but using the page rank data, [LDY ](https://en.wikipedia.org/wiki/City_of_Derry_Airport#Airlines_and_destinations) is not returned because it does not feature in the page rank. This is obviously incorrect, it has 10 times higher passenger traffic than nearby [CFN](https://en.wikipedia.org/wiki/Donegal_Airport) which does feature in the page rank. (Despite not having many passengers, it is [very beautiful](http://cdn4.img.sputniknews.com/images/103889/37/1038893770.jpg)!)

I can't figure out how the page rank is created

In `/opentraveldata/ref_airport_pageranked.csv` it says

> PageRank values (http://en.wikipedia.org/wiki/PageRank) for the 4504 most important travel-related POR (points of reference).

but with no more info than that, `/tools/README` and in I see

> PageRank derived from the flight schedules for a whole year

How do you determine which airports are page ranked, and what criteria are used? (Maybe the beauty of the airport? :smile: )

**Comment by tadhgpearson** [comment]
Closed without an answer, that's a bit harsh @denisarnaud :cry:

**Comment by denisarnaud** [comment]
Well, I provided you with an off-line answer...

**Comment by tadhgpearson** [comment]
Ah - thanks, it got stuck in my spam folder
