### ISSUE TITLE
Missing airlines: Aviastar-TU

### ISSUE THREAD

**Issue by seoker** [opentraveldata/opentraveldata#49]
Hi,

I found there's an airline using the same IATA code `4B`
https://en.wikipedia.org/wiki/Aviastar-TU

I'm not sure how to add a missing airline, any instruction?
Thanks.

**Comment by denisarnaud** [comment]
Added in af1a1ebb64f05d63403b0c0196c8756a01815af1

You can just add the new record in the [opentraveldata/optd_airline_best_known_so_far.csv data file](https://github.com/opentraveldata/opentraveldata/blob/master/opentraveldata/optd_airline_best_known_so_far.csv).

**Comment by seoker** [comment]
Hi, I was just wondering how to naming `pk`, and what's the format of some of columns that contains something like this: `p=en`, what is `p` and what is `h` actually?

**Comment by denisarnaud** [comment]
The semantic of the alternative names follows the [Geonames specification](http://www.geonames.org/manual.html#alternateNames): "language_code | name in that language | specifier".

The specifier can be any combination of:
- `p` means preferred. A single name per language can be preferred
- `h` means historical
- `s` means short

The language code corresponds to the [ISO 639 specification](http://en.wikipedia.org/wiki/ISO_639). A few pseudo-codes are also available, for instance:
- `abbr` for an abbreviation
- `sign` for a call-sign (note that that one is not supported by Geonames)

**Comment by denisarnaud** [comment]
`pk` is the primary key, which is composed of:
- The airline `key`, identifying uniquely a given airline/transportation company. The key remains the same throughout the whole history of the airline/transportation company.  For instance, `air-eastok-avia` corresponds to [Air Bishkek](http://en.wikipedia.org/wiki/Air_Bishkek), Air Bishkek is the third version of the airline (valid from 2011-04-01), which was also named throughout its history Kyrgyz Airways (version 2, from 2010-05-01 to 2011-03-31) and Eastok Avia (version 1, from 2006-06-01 to 2010-04-30).
- The `version`.

The current status of a given airline/transportation company is the one having the latest/max version. As a shortcut, the `env_id` field is empty for the current version of an airline/transportation company. For the airlines no longer referenced by IATA, `env_id` is equal to `version`.
