### ISSUE TITLE
Alliance is missing in optd_airline_best_known_so_far.csv

### ISSUE THREAD

**Issue by seoker** [opentraveldata/opentraveldata#52]
As titled,

Alliance seems to be removed from `optd_airline_best_known_so_far.csv`, but alliance status is still there.

**Comment by denisarnaud** [comment]
Yes, the alliance information is derived from the [opentraveldata/optd_airline_alliance_membership.csv data file](https://github.com/opentraveldata/opentraveldata/blob/master/opentraveldata/optd_airline_alliance_membership.csv). In ``optd_airline_best_known_so_far.csv``, that field is no longer used. We do not drop that column for backward-compatibility issues. For the same backward-compatibility reason, any new column must be added at the right-hand side of the file.
