### ISSUE TITLE
Ambiguous Virgin Australia (VA) records in optd_airlines.csv

### ISSUE THREAD

**Issue by nishaj** [opentraveldata/opentraveldata#59]
Hi Team,

Following are the records we get in airlines files for the Virgin Australia. 

**air-virgin-australia-int-v1^^2009-02-27^^VAU^VA^795^Virgin Australia International^V Australia^^^^http://en.wikipedia.org/wiki/V_Australia^^en|Virgin Australia International|=en|V Australia|^^air-virgin-australia-int^1
air-virgin-australia-regional-v1^^1963-01-01^^VOZ^VA^608^Virgin Australia Regional^SkyWest^^^^http://en.wikipedia.org/wiki/Virgin_Australia_Regional_Airlines^15638^en|Virgin Australia Regional|=en|SkyWest|^^air-virgin-australia-regional^1
air-virgin-australia-v1^^2000-08-31^^VOZ^VA^856^Virgin Australia^Virgin Blue^^^^http://en.wikipedia.org/wiki/Virgin_Australia^15638^en|Virgin Australia|=en|Virgin Blue|^^air-virgin-australia^1**

The issue is that all the three records are valid for departure date after 2009-02-27. Due to the duplication of the IATA code ("VA" here), the schedule reconciliation process is ambiguous.

I am not sure If we can fix the data.

Regards,
Nishaj

**Comment by denisarnaud** [comment]
Thanks Nishaj for spotting this.
Indeed, last week, @aseredyn mentioned Virgin Australia as a tricky example.
I would suggest to merge Virgin Australia and Virgin Australia Regional Airlines, both having the same IATA and ICAO codes (VA/VOZ). "Virgin Australia Regional Airlines" would then become just an alternate name of Virgin Australia (VA/VOZ).

Would you agree with that solution?

Kind regards

Denis

**Comment by nishaj** [comment]
Hi Deni,

If we merge Virgin Australia and Virgin Australia Regional Airlines into one record, We will still have two records in the file one for Virgin Australia International and the merged record. If we don't give a to date/env_id to the virgin Australia International we will still have the same issue when we search by the 2 char Iata code. In Booking Analytics we are not having the ICAO code.

**Comment by nishaj** [comment]
Hi Deni,

Any update on this issue?

Kind Regards
Nishaj
