### ISSUE TITLE
PKL has disappeared from IATA website

### ISSUE THREAD

**Issue by andk** [opentraveldata/opentraveldata#60]
PKL has disappeared from IATA website. Geonames has this as AIRP: http://www.geonames.org/8298860/pakatoa-island.html with iate=PKL, but latlong is very different from the island https://en.wikipedia.org/wiki/Pakatoa_Island (which has same latlong as the ISL http://www.geonames.org/2185067/pakatoa-island.html )

I'm not sure where to start, so I try it with an issue.

Maybe 8298860 needs to be moved to the same location as 2185067 and then the iata code removed?

**Comment by denisarnaud** [comment]
That record does not appear on IATA's web site because it is an off-line point. Indeed, there is no travel-related POR associated to that place.
