### ISSUE TITLE
optd_airlines.csv: Issue with following airlines (JU, FS)

### ISSUE THREAD

**Issue by nishaj** [opentraveldata/opentraveldata#66]
Hi All,

**JU**
In the reference file we have one entry for 9U (Air Serbia) valid from 26th Sep 2013. Before this date (as per wiki) this airline was known as JAT airways. Is it possible to have an entry for that?

**FS**
This Iata code is mapped to two airlines Fly540 Angola (Valid from 1st Jan 2011 to 31st May 2014) and Syphax Airlines (Valid from 29th April 2012). As per the wiki (https://en.wikipedia.org/wiki/Fly540_Angola)  Fly540 Angola's Iata code should have been "F5" instead of "FS". Can you please check the same? (I am not sure if my understanding is correct or not).

Thanks & Regards,
Nishaj

**Comment by alexprengere** [comment]
This looks like it has been fixed for a while.
