### ISSUE TITLE
Comparison between search logs and optd_por_public

### ISSUE THREAD

**Issue by alexprengere** [opentraveldata/opentraveldata#67]
Hi, 
I wrote a script to analyze in search logs and see what requested airports/cities were not in optd_por_public.
Those may very well be typos (like the suspicious NRW), but some cases are more interesting. For example, FFC seems to be [Atlanta Regional Airport](https://en.wikipedia.org/wiki/Atlanta_Regional_Airport), but has no IATA code attributed, "FFC" seems to be an identifier from the FAA.

Anyway, here is the list of codes I found more than once over a few million searches:
```
FFC JRC OPJ HEW KOB IBU NRW FBX XYV TJR NBK NRW AQH GWW HCS GCRE
````
I will try to investigate them, see if this method yields interesting results.

**Comment by denisarnaud** [comment]
Thanks, that is an excellent idea!
