### ISSUE TITLE
Rostov-on-Don Airport IATA code change

### ISSUE THREAD

**Issue by alexprengere** [opentraveldata/opentraveldata#76]
Hello,
It looks like [Rostov-on-Don Airport](https://en.wikipedia.org/wiki/Rostov-on-Don_Airport) changed IATA code after Nov 26, 2017, from ROV to RVI. I believe this change is not reflected in the latest reference file.

**Comment by pgrandjean** [comment]
sorry, wrongly closed the issue!

**Comment by denisarnaud** [comment]
Thanks Alex!

To be more specific, ROV has now two airports:
* ROV, for Platov Airport
* RVI, for Rostov Airport

**Comment by alexprengere** [comment]
I looked at the generated file, and it has 3 lines for ROV. I understand one is for the deprecated airport, the other one is for the city, and I think the extra one is a bug but I could be mistaken.

**Comment by denisarnaud** [comment]
1. [One is the new Platov International Airport, ROV, active](https://github.com/opentraveldata/opentraveldata/commit/e0db402656bf72e9e4d9dab08d84c0f89b56bbe7#diff-bd88c7fade35cd1067313b43ddc241f8R13102)
2. [One is the older Rostov-on-Don Airport, RVI, active](https://github.com/opentraveldata/opentraveldata/commit/e0db402656bf72e9e4d9dab08d84c0f89b56bbe7#diff-bd88c7fade35cd1067313b43ddc241f8R13237)
3. [One is the city, ROV, active](https://github.com/opentraveldata/opentraveldata/commit/e0db402656bf72e9e4d9dab08d84c0f89b56bbe7#diff-bd88c7fade35cd1067313b43ddc241f8R13104)
4. And [the last one is the deprecated code for Rostov-on-Don Airport, ROV](https://github.com/opentraveldata/opentraveldata/commit/e0db402656bf72e9e4d9dab08d84c0f89b56bbe7#diff-bd88c7fade35cd1067313b43ddc241f8R13103). In other words, what is deprecated (no longer active) is not the airport itself, but the fact that it was referenced by the ROV IATA code.

**Comment by alexprengere** [comment]
You are right, I missed the fact that ROV is now the IATA code of another active airport. Mystery solved, thanks! :wink:
