### ISSUE TITLE
Please add F3 - Flyadeal to the optd_airlines.csv file

### ISSUE THREAD

**Issue by deepak0000** [opentraveldata/opentraveldata#81]
Hello,

I notice that F3 - Flyadeal is missing from your optd_airlines.csv file.
Wiki link for reference  - https://en.wikipedia.org/wiki/Flyadeal

Best,
Deepak

**Comment by denisarnaud** [comment]
Fixed with 12fe412a1df5207ee5d5eb84758a99c093363600

**Comment by denisarnaud** [comment]
Thanks for your contribution, Deepak!
