### ISSUE TITLE
YEH has no coordinates

### ISSUE THREAD

**Issue by alexprengere** [opentraveldata/opentraveldata#83]
In the latest revision of the optd por file, YEH has no coordinates (it had them before the update).

**Comment by denisarnaud** [comment]
The IATA code has been suppressed by [some user](http://www.geonames.org/recent-changes/user/jnyrup/) on Geonames: http://www.geonames.org/1785885/yueyahu.html
I just re-added the IATA code. But I am not sure it is a good thing.

Indeed, for the airport itself, there are at least two options:
* [Yinchuan Helanshan Airport](http://www.geonames.org/11493676/yinchuan-helanshan-airport.html)
* [Yueyahuxiang, Xingqing, Yinchuan, Ningxia, China](https://goo.gl/maps/9ftGcDf9grQ2)
The first option seems more logical, but it does not correspond to IATA naming: http://www.iata.org/publications/Pages/code-search.aspx
There seems to be a mix, on the IATA database, between the city and the airport names.

Note that the [city of Yinchuan](http://www.geonames.org/1786657/yinchuan.html) is itself referred to by IATA as INC, and the associated airport is [Yinchuan Hedong Airport](http://www.geonames.org/6301883/yinchuan-hedong-airport.html).

For now, I assumed that IATA made an error on the name of the airport, and picked [Yinchuan Helanshan Airport](http://www.geonames.org/11493676/yinchuan-helanshan-airport.html) as the YEH airport. I assumed that the served city is INC, ie, [Yinchuan](http://www.geonames.org/1786657/yinchuan.html).
