### ISSUE TITLE
Empty city name lists

### ISSUE THREAD

**Issue by alexprengere** [opentraveldata/opentraveldata#9]
Currently every por of the ``optd_por_public.csv`` file has:
* always a non-empty ``name`` field
* always a non-empty ``city_code_list`` field

This is great! It means that such code never raises ``IndexError``:
```python
from GeoBases import GeoBase
g = GeoBase(data='ori_por', verbose=False)
g.get('ADJ', 'city_code_list')[0]
```
This is really nice because this is really frequent, as mentioned in [this issue](https://github.com/opentraveldata/optd/issues/29). But you would think that if every por has a non-empty ``name`` and a non-empty ``city_code_list``:
* it should always have a non-empty ``city_name_list``
* the ``city_code_list`` and ``city_name_list`` should have the same size

This is *not* currently the case.

I think the ``city_name_list`` should be a *simple* iteration of the field ``name`` for each element of the ``city_code_list``. We *could* remove duplicates, when cities with same iata codes have different names, so ``city_name_list`` could actually be longer than ``city_code_list``. Anyway, it should never be empty, and no ``IndexError`` should occur when attempting to access the name of the main city with ``g.get(por, 'city_name_list')[0]``.

I created a gist [here](https://gist.github.com/alexprengere/5607b1502afd9ecde54e) logging all pors with empty ``city_name_list``, 804 with the latest data. The output of the script is enclosed in the gist, otherwise the usage is simple:
```bash
$ python check_names.py
QPF with name Pompeia SP BR Off has city_code_list ('QPF',) and city_name_list ()
ZZL with name Larbaâ has city_code_list ('ZZL',) and city_name_list ()
XPC with name Port Canaveral has city_code_list ('XPC',) and city_name_list ()
ZVV with name Dutch Rail Zone 11 NL Off Line has city_code_list ('ZVV',) and city_name_list ()
...
```

**Comment by denisarnaud** [comment]
The issue still persists with the airports having no IATA code. Those airports have only a ICAO code (and their IATA code is set to "ZZZ"). Hence, the city cannot be derived (at least, without having to rework the full stack) for those airports.
If you prefer, we could set a specific city name, such as "Zzzz"; but I guess that empty fields are better here.
