### ISSUE TITLE
Please add LV - Level Airlines to the optd_airlines.csv file

### ISSUE THREAD

**Issue by deepak0000** [opentraveldata/opentraveldata#92]
Hello,

I notice that LV- Level Airlines is missing from your optd_airlines.csv file.
Wiki link for reference - https://en.wikipedia.org/wiki/Level_(airline)

Best,
Deepak

**Comment by denisarnaud** [comment]
Please note that:
* [IATA](http://www.iata.org/publications/Pages/code-search.aspx) states that ``LV`` references [OpenSkies](http://en.wikipedia.org/wiki/OpenSkies), not Level. I agree that OpenSkies operates part of Level's traffic, though.
* The Level Wikipedia pages, in all the other languages than English (for instance the [Spanish one](http://es.wikipedia.org/wiki/LEVEL)) reference Level as sharing Iberia's codes (ie, IB/IBE).

So, it is not fully clear that LV should reference Level. Do not hesitate to bring forward some additional pieces of information about it.

**Comment by deepak0000** [comment]
Thank you, that is very interesting!
