### ISSUE TITLE
Please add MRB- Muara Bungo Airport to the optd_por_public.csv file

### ISSUE THREAD

**Issue by deepak0000** [opentraveldata/opentraveldata#94]
Hello,

I notice that MRB- Muara Bungo Airport is missing from your optd_por_public.csv file.
Wiki link for reference - https://en.wikipedia.org/wiki/Muara_Bungo_Airport

Best,
Deepak

**Comment by denisarnaud** [comment]
Hi Deepak,

thanks for your contribution!

Please note that MRB designates [Eastern West Virginia Regional Airport, West Virginia (WV), United States (US)](http://www.geonames.org/4804783/eastern-west-virginia-regional-airport.html), not the Muara Bungo Airport, Indonesia (ID), as you can check on [IATA](https://www.iata.org/publications/Pages/code-search.aspx).
