### ISSUE TITLE
Missing airlines with IATA code

### ISSUE THREAD

**Issue by vrampal** [opentraveldata/opentraveldata#95]
Hello,

I tried to use opentraveldata to decode ADS-B packets and information from RadarBox24.
I found several missing airlines, here are the one I was able to identify.
All data comes from real flying plane + cross checked on IATA website.

5X -> UPS Airline
https://en.wikipedia.org/wiki/UPS_Airlines

RW -> Royal Air Charter
https://en.wikipedia.org/wiki/Royal_Air_Charter

GB -> ABX Air
https://en.wikipedia.org/wiki/ABX_Air

PO -> Polar Air Cargo
https://en.wikipedia.org/wiki/Polar_Air_Cargo

4R -> Star East Airline S.R.L.
https://www.planespotters.net/airline/Star-East-Airlines
https://www.airfleets.net/flottecie/Star%20East%20Airlines.htm

9S -> Southern Air
https://en.wikipedia.org/wiki/Southern_Air

VO -> VLM Airlines
https://en.wikipedia.org/wiki/VLM_Airlines

M6 -> Amerijet International
https://en.wikipedia.org/wiki/Amerijet_International

CY -> Charlie Airlines (Cyprus Airways)
https://en.wikipedia.org/wiki/Charlie_Airlines

CS -> Comlux Aruba NV

D0 -> DHL Air UK
https://en.wikipedia.org/wiki/DHL_Air_UK

A4 -> Azimuth
https://en.wikipedia.org/wiki/Azimuth_(airline)

GG -> Sky Lease Cargo
https://en.wikipedia.org/wiki/Sky_Lease_Cargo

JA -> JetSmart
https://en.wikipedia.org/wiki/JetSmart

KZ -> Nippon Cargo Airlines
https://en.wikipedia.org/wiki/Nippon_Cargo_Airlines

VV -> Viva Air Peru
https://en.wikipedia.org/wiki/Viva_Air_Peru

ES -> DHL International Aviation ME
ES -> Estelar Latinoamerica
https://en.wikipedia.org/wiki/DHL_International_Aviation_ME
https://en.wikipedia.org/wiki/Estelar_Latinoamerica

KH -> Aloha Air Cargo
https://en.wikipedia.org/wiki/Aloha_Air_Cargo

Hoping you can include these airlines in a next release.

Regards,
Vincent

**Comment by vrampal** [comment]
Ok, I found a way to dump all IATA airlines directly from their search page:
https://www.iata.org/publications/Pages/code-search.aspx

Here is the full list:
https://gist.github.com/vrampal/89b1574b194977c958f22209be7bac1e

**Comment by denisarnaud** [comment]
> Here is the full list: https://gist.github.com/vrampal/89b1574b194977c958f22209be7bac1e

Thanks!

A [specific data file](https://github.com/opentraveldata/opentraveldata/blob/master/data/IATA/archives/iata_airline_list_20180808.csv) has been added to the [``data/IATA`` directory](https://github.com/opentraveldata/opentraveldata/blob/master/data/IATA/archives) with a format more convenient for data analysis by machines.

**Comment by denisarnaud** [comment]
All the airlines described in your list have now been added (or amended, wherever needed).
A great thanks for that contribution!
